version: '2'
services:
  application:
    image: euclid1990/ubuntu-server
    hostname: server
    volumes:
      - ./var/www/html:/usr/local/apache2/htdocs/note
  mariadb:
    image: mariadb
    hostname: mysql  
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: note
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./var/log/mysql:/var/log/mysql
  php:
    image: euclid1990/php5.6-fpm
    hostname: php
    ports:
      - "6666:9000"
    volumes_from:
      - application
    links:
      - mariadb:mysql
  apache:
    image: httpd
    hostname: apache
    ports:
      - '7777:80'
      - '443:443'
    links:
      - php  
    volumes_from:
      - application  
    volumes:
      - ./var/log/apache2:/var/log/apache2
      - ./etc/apache2/conf-enabled:/etc/apache2/conf-enabled/    