version: '2'
services:
  application:
    image: euclid1990/ubuntu-server
    hostname: server
    volumes:
      - ./var/www/html:/var/www/html
  mariadb:
    image: mariadb
    hostname: mysql  
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php5
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/data:/mysql/data
      - ./var/log/mysql:/var/log/mysql
  php:
    image: euclid1990/php5.6-fpm
    hostname: php
    ports:
      - "5050:9000"
    volumes_from:
      - application
    links:
      - mariadb:mysql
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "5555:80"
    links:
      - php
    volumes_from:
      - application
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
